[meta]
title = "FastAPI Voice Agent Starter"
description = "Get started using Deepgram's Voice Agent with this FastAPI demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
repository = "https://github.com/deepgram-starters/fastapi-voice-agent"
useCase = "Voice Agent"
language = "Python"
framework = "FastAPI"

[build]
command = "make init"

[dev]
command = "make dev"
